# Calculadora Estatatistica em Matriz 3X3

Rode o código abaixo:

In [31]:
#importa as bibliotecas necessarias
import numpy as np 
import pandas as pd

### Inserir a Lista

Rode o código abaixo, e insira sua lista de 9 numeros separados por virgúla e caso o número seja decimal deve ser dividido por ponto. 
Ex.: [1, 1.4, 1.3, 4, 5, 6, 7, 8.8, 9]

In [32]:
entrada = input()
lista = entrada.split(',')

# Verifica se todos os elementos podem ser convertidos para float
try:
    lista_float = [float(num.strip()) for num in lista]
except ValueError:
    print("Aviso: A lista contém elementos que não são float.")
else:
    # Verifica o tamanho da lista
    if len(lista_float) != 9:
        print("Aviso: A lista deve conter exatamente 9 números.")
    else:
        print(lista_float)

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]


### Plotar a Matriz

Rode o código abaixo e veja sua matriz:
    Caso dê algum erro, atente-se ao tipo do erro e corrija sua lista na fase anterior.

In [33]:
# Verifica se a lista_float foi criada corretamente
if 'lista_float' in locals():
    matriz = np.array(lista_float).reshape(3, 3)

    def verificar_array(arr):
        # Verifica se todos os elementos são float
        if not np.issubdtype(arr.dtype, np.floating):
            raise ValueError("O array deve conter apenas números.")
        # Verifica o tamanho do array
        elif arr.size != 9:
            raise ValueError("O array deve conter nove números.")
        else:
            print(arr)

    # Verificação do array
    verificar_array(matriz)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


## Operações com a matriz


### Soma

#### Soma das Colunas

In [34]:
soma_das_colunas = np.sum(matriz, axis=0)
print('A soma de cada coluna 1,2,3 respectivamente é:', soma_das_colunas)

A soma de cada coluna 1,2,3 respectivamente é: [ 9. 12. 15.]


#### Soma das Linhas

In [35]:
soma_das_linhas = np.sum(matriz, axis=1)
print('A soma de cada linha 1,2,3 respectivamente é:', soma_das_linhas)

A soma de cada linha 1,2,3 respectivamente é: [ 3. 12. 21.]


#### Soma dos Elementos

In [36]:
soma_matriz = np.sum(matriz)
print('A soma de todos os elementos da matriz é:', soma_matriz)

A soma de todos os elementos da matriz é: 36.0


In [51]:
Soma = [print("[", soma_das_colunas, "," , soma_das_linhas,", ", soma_matriz ,"]") ]

[ [ 9. 12. 15.] , [ 3. 12. 21.] ,  36.0 ]


#### Média


In [57]:
média_matriz = np.mean(matriz)
print("A média dos valores é:",média_matriz)

A média dos valores é: 4.0


In [53]:
média_coluna = np.mean(matriz, axis=0)
print("A média dos valores é:",média_coluna)

A média dos valores é: [3. 4. 5.]


In [56]:
média_linha = np.mean(matriz, axis= 1)
print("A média dos valores é:",média_linha)

A média dos valores é: [1. 4. 7.]


In [58]:
Média = [print("[", média_coluna, "," , média_linha,", ", média_matriz ,"]") ]

[ [3. 4. 5.] , [1. 4. 7.] ,  4.0 ]


#### Variância

In [38]:
variancia = np.var(matriz)
print("A Variância dos valores é:",variancia)

A Variância dos valores é: 6.666666666666667


#### Desvio Padrão


In [39]:
dp = np.std(matriz)
print("O desvio padrão da matriz é:", dp)

O desvio padrão da matriz é: 2.581988897471611


##### Máximo

In [40]:
desvio_padrao_max = np.max(np.std(matriz)) 
print("O desvio padrão máx da matriz é:", desvio_padrao_max)


O desvio padrão máx da matriz é: 2.581988897471611


##### Minimo

In [41]:
desvio_padrao_min = np.min(np.std(matriz))
print("O desvio padrão min da matriz é:", desvio_padrao_min)

O desvio padrão min da matriz é: 2.581988897471611


SyntaxError: invalid syntax (2618086143.py, line 1)