# Calculadora Estatatistica em Matriz 3X3

Rode o código abaixo:

In [26]:
#importa as bibliotecas necessarias
import numpy as np 
import pandas as pd

### Inserir a Lista

Rode o código abaixo, e insira sua lista de 9 numeros separados por virgúla e caso o número seja decimal deve ser dividido por ponto. 
Ex.: [1, 1.4, 1.3, 4, 5, 6, 7, 8.8, 9]

In [ ]:
entrada = input()
lista = entrada.split(',')

# Verifica se todos os elementos podem ser convertidos para float
try:
    lista_float = [float(num.strip()) for num in lista]
except ValueError:
    print("Aviso: A lista contém elementos que não são float.")
else:
    # Verifica o tamanho da lista
    if len(lista_float) != 9:
        print("Aviso: A lista deve conter exatamente 9 números.")
    else:
        print(lista_float)

### Plotar a Matriz

Rode o código abaixo e veja sua matriz:
    Caso dê algum erro, atente-se ao tipo do erro e corrija sua lista na fase anterior.

In [49]:
# Verifica se a lista_float foi criada corretamente
if 'lista_float' in locals():
    matriz = np.array(lista_float).reshape(3, 3)

    def verificar_array(arr):
        # Verifica se todos os elementos são float
        if not np.issubdtype(arr.dtype, np.floating):
            raise ValueError("O array deve conter apenas números.")
        # Verifica o tamanho do array
        elif arr.size != 9:
            raise ValueError("O array deve conter nove números.")
        else:
            print(arr)

    # Verificação do array
    verificar_array(matriz)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Operações com a matriz


#### Soma das Colunas

In [50]:
soma_das_colunas = np.sum(matriz, axis=0)
print('A soma de cada coluna 1,2,3 respectivamente é:', soma_das_colunas)

A soma de cada coluna 1,2,3 respectivamente é: [12. 15. 18.]


#### Soma das Linhas

In [52]:
soma_das_linhas = np.sum(matriz, axis=1)
print('A soma de cada linha 1,2,3 respectivamente é:', soma_das_linhas)

A soma de cada linha 1,2,3 respectivamente é: [ 6. 15. 24.]


#### Soma dos Elementos

In [54]:
soma_matriz = np.sum(matriz)
print('A soma de todos os elementos da matriz é:', soma_matriz)

A soma de todos os elementos da matriz é: 45.0


#### Variância

#### Média


#### Desvio Padrão


##### Máximo

##### Minimo